# Simplified Docker Compose for EPIC-secuTrial Pipeline
version: '3.8'

services:
  epic-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epic-pipeline
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs  
    environment:
      - BASE_DIR=/app/data
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - epic-network
    # Uncomment to run both validation and import
    # command: >
    #   sh -c "python /app/validation-service/src/main.py && 
    #          python /app/import-service/src/main.py"

networks:
  epic-network:
    driver: bridge